### PR TITLE
Feat/refactor repo

### PR DESCRIPTION
**Pull request by edgarriba**
This is a first pull request towards a differentiable generic computer vision framework.
Package renaming is coming :clock1: 

At first, we propose the following sub-modules:

- `color`: perform color space conversions
- `contrib`: user contrib and experimental operators
- `features`: feature detection
- `filters`: image filtering
- `geometry`: image transformations, linear transformation, conversions, camera models and warping
  - `camera`
  - `conversions`
  - `linalg`
  - `transform`
  - `warp`
- `losses`: stack of vision loss functions
- `utils`: handy utilities for conversions
  - `image`
  - `metrics`

**_UPDATE (16/05/2019):_**

after a talk with @spmallick, he proposes the following:
- remove or not expose `utils` to user to avoid people adding useless stuff in such module.
- split geometry in 2d transforms and camera geometry:
  - we might want to keep `geometry` for geometrical image transformations and `calibration` for camera geometry and 3d reconstruction (similar to calib3d from opencv).

**_UPDATE (21/05/2019):_**

after internal meeting, @amayeh  proposes to split the `geometry` module in:
- `geometry.transform`: high level routines to perform 2D image transformations.
- `geometry.linalg`: linear algebra library to perform 3D transformations.
- `geometry.camera`: API for different camera model representations.
- `geometry.conversions`: stack of routines to perform different geometric system conversion.
- `geometry.warp`: base functionalities to perform warping.

we will keep by now `utils` and we'll place there helper routines for visual debugging and place `metrics` inside.

### CODE REVIEW

**Comment by edgarriba** [comment]
@bhack @ethanrublee @garybradski any thoughts about this reorganization, renaming, etc ?

**Comment by ducha-aiki** [comment]
I always felt that "calibration" is wrong name. geometry3d is more broad and correct imo.
Agree that utils is bad name :)

**Comment by edgarriba** [comment]
@ducha-aiki check my updated comment. We'll split geometry in different topics. I agree about utils, by now it will contain some routines to help visual debug:
- `utils.tensor_to_image`
- `utils.image_to_tensor`
- `utils.create_meshgrid`
- `utils.batch_to_image`

**Comment by ducha-aiki** [comment]
Might be also structure features to 

- features.detector
- features.descriptors ?

**Comment by edgarriba** [comment]
@ducha-aiki sure

**Pull request merged**
